### ISSUE TITLE
Crash of dokuwiki on a stick, no restart possible. Only this info in browser.

### ISSUE THREAD

**Issue by martk70** [hafron/dokuwiki-plugin-bez#3]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in C:\_prog\DokuWikiStick\dokuwiki\lib\plugins\bez\mdl\model.php:37 Stack trace: #0 C:\_prog\DokuWikiStick\dokuwiki\lib\plugins\bez\mdl\model.php(37): PDO->__construct('sqlite:/C:\_pro...') #1 C:\_prog\DokuWikiStick\dokuwiki\lib\plugins\bez\syntax\nav.php(67): BEZ_mdl_Model->__construct(Object(auth_plugin_authplain), NULL, 'en') #2 C:\_prog\DokuWikiStick\dokuwiki\inc\plugincontroller.class.php(109): syntax_plugin_bez_nav->__construct() #3 C:\_prog\DokuWikiStick\dokuwiki\inc\pluginutils.php(45): Doku_Plugin_Controller->load('syntax', 'bez_nav', false, false) #4 C:\_prog\DokuWikiStick\dokuwiki\inc\parserutils.php(538): plugin_load('syntax', 'bez_nav') #5 C:\_prog\DokuWikiStick\dokuwiki\inc\parserutils.php(190): p_get_parsermodes() #6 C:\_prog\DokuWikiStick\dokuwiki\inc\parserutils.php(167): p_get_instructions('~~NOTOC~~?<WRAP...') #7 C:\_prog\DokuWikiStick\dokuwiki\inc\parserutils.php(480): p_cached_instructions(' in C:\_prog\DokuWikiStick\dokuwiki\lib\plugins\bez\mdl\model.php on line 37

**Comment by hafron** [comment]
It seems like your web server doesn't have permission to read database file. /path/to/your/dokuwiki/data/bez.sqlite should be writable by web server. You can always turn off BEZ by creading empty file named: "disabled" in /path/to/your/dokuwiki/lib/plugins/bez/ is you only need to make your dokuwiki work again.

**Comment by hafron** [comment]
I haven't tested BEZ on Windows. It may be some platform issue.

**Comment by martk70** [comment]
Using Windows 7, and I think dokuwiki on a stick has other / no authorization system with a minimal configuration. It is on the dokuwiki download page.  I thought I should mention it, but please remove the information if you think this is no longer relevant.


----- Original Message ----

From: Szymon Olewniczak 

To: hafron/dokuwiki-plugin-bez 

Cc: martk70 , Author 

Sent: Din, 10 Jan 2017 10:08

Subject: Re: [hafron/dokuwiki-plugin-bez] Crash of dokuwiki on a stick, no restart possible. Only this info in browser. (#3)




I haven't tested BEZ on Windows. It may be some platform issue.
